# Generated by Django 5.0.4 on 2024-08-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
    ]
